apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: navidrome
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "appLabels" . | nindent 4 }}
spec:
  secretName: navidrome
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - navidrome.ef6ea7c0-f649-4c64-a06f-d07d6cad68cc.lb.civo.com
  - navidrome-uploader.ef6ea7c0-f649-4c64-a06f-d07d6cad68cc.lb.civo.com