apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: navidrome
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "appLabels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secret }}
  issuerRef:
    name: {{ .Values.clusterissuer.privateKeySecretRef.name }}
    kind: ClusterIssuer
  dnsNames:
  - navidrome.{{ include "baseDomain" . }}
  - navidrome-uploader.{{ include "baseDomain" . }}