apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: navidrome
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "appLabels" . | nindent 4 }}
spec:
  secretName: navidrome
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - demo.0d652485-6bb6-465f-b3b3-eb12485d9aee.lb.civo.com