apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterissuer.name }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "appLabels" . | nindent 4 }}
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.clusterissuer.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.clusterissuer.name }}
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: traefik