apiVersion: v1
kind: ConfigMap
metadata:
  name: navidrome-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "appLabels" . | nindent 4 }}
data:
  ND_ENABLEUSEREDITING: "false"