apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "appLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi