apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "appLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "commonLabels" . | nindent 6 }}
      app: navidrome
  template:
    metadata:
      labels:
        {{- include "commonLabels" . | nindent 8 }}
        app: navidrome
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - navidrome
              topologyKey: kubernetes.io/hostname
      containers:
      - name: navidrome
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: navidrome-config
        ports:
        - containerPort: {{ .Values.containerPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: music-volume
          mountPath: /music
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-volume
      - name: music-volume
        persistentVolumeClaim:
          claimName: music-volume