apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "appLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "commonLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "commonLabels" . | nindent 8 }}
    spec:
      containers:
      - name: navidrome
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: music-volume
          mountPath: /music
      volumes:
      - name: data-volume
        emptyDir: {}
      - name: music-volume
        emptyDir: {}