apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: navidrome
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "appLabels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`navidrome.{{ include "baseDomain" . }}`)
      kind: Rule
      middlewares:
        - name: rate-limit
        - name: security-headers
      services:
        - name: navidrome
          port: 80
    - match: Host(`navidrome-uploader.{{ include "baseDomain" . }}`)
      kind: Rule
      middlewares:
        - name: rate-limit
        - name: security-headers
      services:
        - name: filebrowser
          port: 80
  tls:
    secretName: navidrome-tls