apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: navidrome
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "appLabels" . | nindent 4 }}
spec:
  ingressClassName: traefik
  rules:
  - host: navidrome.{{ include "baseDomain" . }}
    http:
      paths:
      - backend:
          service:
            name: navidrome
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: navidrome-uploader.{{ include "baseDomain" . }}
    http:
      paths:
      - backend:
          service:
            name: filebrowser
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - navidrome.{{ include "baseDomain" . }}
    - navidrome-uploader.{{ include "baseDomain" . }}
    secretName: {{ .Values.certificate.secret }}
