apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
  name: nginx-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "appLabels" . | nindent 4 }}
spec:
  rules:
  - host: navidrome.ef6ea7c0-f649-4c64-a06f-d07d6cad68cc.lb.civo.com
    http:
      paths:
      - backend:
          service:
            name: navidrome
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: navidrome-uploader.ef6ea7c0-f649-4c64-a06f-d07d6cad68cc.lb.civo.com
    http:
      paths:
      - backend:
          service:
            name: filebrowser
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - navidrome.ef6ea7c0-f649-4c64-a06f-d07d6cad68cc.lb.civo.com
    - navidrome-uploader.ef6ea7c0-f649-4c64-a06f-d07d6cad68cc.lb.civo.com
    secretName: navidrome
