apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.longhorn.namespaceOverride }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "appLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"