# Application settings
namespace: navidrome-system
replicaCount: 2
image:
  repo: "deluan/navidrome"
  tag: "0.58.5"
  pullPolicy: IfNotPresent
containerPort: 4533
resources:
  limits:
    memory: 400Mi
  requests:
    cpu: 100m

# Service configuration
service:
  type: LoadBalancer
  port: 80

filebrowser:
  imageURI: "filebrowser/filebrowser:v2.59.0"
  reconfigImageUri: "ghcr.io/semmet95/navidrome-deployer/filebrowser-reconfig:0.12.1"
  containerPort: 80
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
  service:
    port: 80