# Application settings
namespace: navidrome-system
replicaCount: 2
image:
  repo: "deluan/navidrome"
  tag: "0.58.5"
  pullPolicy: IfNotPresent
containerPort: 4533
resources:
  limits:
    memory: 400Mi
  requests:
    cpu: 100m

# Service configuration
service:
  type: LoadBalancer
  port: 80

filebrowser:
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m