apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "commonLabels" . | nindent 6 }}
      app: filebrowser
  template:
    metadata:
      labels:
        {{- include "commonLabels" . | nindent 8 }}
        app: filebrowser
    spec:
      # initContainers:
      # - name: filebrowser-config
      #   image: {{ .Values.filebrowser.imageURI }}
      #   command: ['sh', '-c', 'cd database && filebrowser config init -s']
      #   volumeMounts:
      #   # - name: filebrowser-config
      #   #   mountPath: /config
      #   - name: filebrowser-database
      #     mountPath: /database
      containers:
      - name: filebrowser
        image: {{ .Values.filebrowser.imageURI }}
        # lifecycle:
        #   postStart:
        #     exec:
        #       command:
        #       - /bin/sh
        #       - -c
        #       - cd /database && filebrowser config set -s
        ports:
        - containerPort: {{ .Values.filebrowser.containerPort }}
        resources:
          requests:
            cpu: {{ .Values.filebrowser.resources.requests.cpu }}
          limits:
            memory: {{ .Values.filebrowser.resources.limits.memory }}
        volumeMounts:
        # - name: filebrowser-config
        #   mountPath: /config
        - name: filebrowser-database
          mountPath: /database
        - name: music-volume
          mountPath: /srv
      volumes:
      # - name: filebrowser-config
      #   persistentVolumeClaim:
      #     claimName: filebrowser-config
      - name: filebrowser-database
        persistentVolumeClaim:
          claimName: filebrowser-database
      - name: music-volume
        persistentVolumeClaim:
          claimName: music-volume