apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebrowser-config-sa
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: filebrowser-config-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["apps", "v1", ""]
  resources: ["deployments", "pods"]
  resourceNames: ["filebrowser"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  resourceNames: ["filebrowser"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["v1", ""]
  resources: ["pods", "pods/log"]
  verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filebrowser-config-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: filebrowser-config-sa
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: filebrowser-config-role
  apiGroup: rbac.authorization.k8s.io
