name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: 1.24
  KUBECONFIG: '/etc/rancher/k3s/k3s.yaml'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-kubectl@v4
      id: install
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
    - name: Set up test environment
      shell: bash
      run: sudo scripts/test-setup.sh
    - uses: helmfile/helmfile-action@v2.0.4
      with:
        helmfile-args: apply
        helm-version: v3.19.2
        helmfile-auto-init: "true"
    # - name: Run E2E tests
    #   shell: bash
    #   run: |
    #     set -ex
    #     mage test:deployApp