name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: 1.24
  KUBECONFIG: '/etc/rancher/k3s/k3s.yaml'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-kubectl@v4
      id: install
    - uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
    - name: Set up test environment
      shell: bash
      run: |
        scripts/test-setup.sh
    - name: Longhorn Preflight Checks
      shell: bash
      run: |
        scripts/longhorn-preflight.sh
    - uses: helmfile/helmfile-action@v2.0.4
      with:
        helmfile-args: apply
        helm-version: v3.19.2
        helmfile-workdirectory: test
    - name: Run Mage E2E Tests
      uses: magefile/mage-action@v3
      with:
        version: latest
        args: test:deployApp